name: Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          username: InsomaniacElf   # 👈 your GitHub username
          color: yellow             # Pacman color (you can change)
          output: pacman.svg        # Output file name

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pacman.svg
          git commit -m "Update Pacman contribution graph"
          git push
