name: Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          username: InsomaniacElf   # 👈 your GitHub username
          color: yellow             # Pacman color (you can change)
          output: pacman.svg        # Output file name

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pacman.svg
          git commit -m "Update Pacman contribution graph"
          git push


name: generate pacman game

on:
schedule: # Run automatically every 24 hours
    - cron: "0 */24 * * *"
workflow_dispatch: # Allows manual triggering
push: # Runs on every push to the main branch
    branches:
    - main

jobs:
generate:
    permissions:
    contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
        github_user_name: InsomaniacElf

    # Push the generated SVG to the output branch
    - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
        target_branch: output
        build_dir: dist
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
