name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # runs daily
  workflow_dispatch:     # allows manual run

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate pacman contribution graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: InsomaniacElf
          THEME: pacman

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update Pacman contribution graph" || echo "No changes to commit"
          git push
